### ISSUE TITLE
Error installing SERVER SIDE

### ISSUE THREAD

**Issue by acaliaro** [shivammaindola/AndroidWebRTC#1]
Hi
I am following these "SERVER SIDE" instructions:

https://medium.com/@shivammaindola07/step-by-step-guide-to-build-webrtc-native-android-app-47898caa1594

I have this error:
![image](https://user-images.githubusercontent.com/5759350/95709378-d1b9b580-0c5e-11eb-9dfb-96c7b5240b3b.png)

Can you help me?
Thanks
Alessandro

**Comment by akwakwak6** [comment]
Hi, I had the same issue, I just forgot to type npm install
![image](https://user-images.githubusercontent.com/47768056/98607238-13cf2900-22e9-11eb-80d0-081a42d23fea.png)
after it works, on port 3000
